#pragma once  
#include <Core/StateManager.hpp> 
#include "GameState.hpp"
#include "Menu.hpp"
#include "LevelsMenu.hpp"
#include "OptionMenu.hpp"
#include "Play.hpp"
#include "PauseMenu.hpp"
#include "QuitGame.hpp"
#include "GameOver.hpp"